# Generated by Django 3.0.8 on 2020-07-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
    ]
