# Generated by Django 3.0.8 on 2020-07-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0002_auto_20200714_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
